name: widgets_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  animate_do: ^3.3.4
  dots_indicator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.2.0
  go_router: ^14.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.5
  custom_lint: ^0.5.11
  riverpod_generator: ^2.2.0
  riverpod_lint: ^2.3.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/